CREATE EXTENSION IF NOT EXISTS CITEXT;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email CITEXT UNIQUE NOT NULL,
    login CITEXT UNIQUE NOT NULL,
    score INTEGER DEFAULT 0,
    password TEXT NOT NULL
);
