CREATE EXTENSION IF NOT EXISTS CITEXT;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS answers;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email CITEXT UNIQUE NOT NULL,
    login CITEXT UNIQUE NOT NULL,
    score INTEGER DEFAULT 0,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS questions (
    id SERIAL NOT NULL PRIMARY KEY,
    theme citext,
    question TEXT
);

CREATE TABLE IF NOT EXISTS answers (
    id SERIAL NOT NULL PRIMARY KEY,
    question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE NOT NULL,
    correct BOOLEAN,
    answer TEXT
);
